#version: '3.8'
#
#services:
#  app:
#    build: ../
#    ports:
#      - "8080:80"
#  mysql:
#    image: mysql:8.0
#    restart: on-failure
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=web
#      - MYSQL_DATABASE=webtech2
#      - MYSQL_USER=web
#      - MYSQL_PASSWORD=web
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

version: "3"
services:
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../SZ:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: webtech2
      MYSQL_USER: web
      MYSQL_PASSWORD: web
      MYSQL_ROOT_PASSWORD: web
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql