<?php
$lang = array(
    "title" => "Main Page",
    "login" => "Login",
    "email" => "Email",
    "invalid_email" => "Enter the correct email.",
    "password" => "Password",
    "invalid_password" => "Enter the correct password.",
    "login_button" => "Log In",
    "view_tasks" => "Overview of tasks",
    "generate_task" => "Generate task",
    "task_set_name" => "Task Set Name",
    "task_number" => "Task number",
    "task_state" => "State of a task",
    "received_points" => "Points received for a task",
    "points_for_task" => "Max points for a task",
    "no_tasks" => "No tasks were found",
    "all_students" => "All students",
    "student" => "Student",
    "add_file" => "Add file",
    "student_name" => "Student name",
    "num_listed_tasks" => "Number of listed tasks",
    "num_submit_tasks" => "Number of submitted tasks",
    "points_received" => "Scored points",
    "max_points" => "Max points",
    "file" => "File: ",
    "file_tasks_points" => "Number of points for tasks in file: ",
    "add_deadline" => "Do you want to add a submission deadline?",
    "deadline" => "Deadline date: ",
    "result" => "Result",
    "result_correctness" => "Correctness of the result",
    "show" => "Show",
    "unsubmitted" => "Unsubmitted",
    "submitted" => "Submitted",
    "submit" => "Submit"
);

?>