<?php
$lang = array(
    "title" => "Hlavná Stránka",
    "login" => "Prihlásenie",
    "email" => "Email :)",
    "invalid_email" => "Zadaj správny email.",
    "password" => "Heslo",
    "invalid_password" => "Zadaj správne heslo.",
    "login_button" => "Prihlásiť",
    "view_tasks" => "Prehľad príkladov",
    "generate_task" => "Vygeneruj príklad",
    "task_set_name" => "Meno Sady Úloh",
    "task_number" => "Číslo úlohy",
    "task_state" => "Stav úlohy",
    "received_points" => "Počet získaných bodov za príklad",
    "points_for_task" => "Max. počet bodov za príklad",
    "no_tasks" => "Nemáte žiadne príklady",
    "all_students" => "Všetci študenti",
    "student" => "Študent",
    "add_file" => "Pridať súbor",
    "student_name" => "Meno študenta",
    "num_listed_tasks" => "Počet vypísaných úloh",
    "num_submit_tasks" => "Počet odovzdaných úloh",
    "points_received" => "Získaný počet bodov",
    "max_points" => "Maximálny počet bodov",
    "file" => "Súbor: ",
    "file_tasks_points" => "Počet bodov za príklady v súbore: ",
    "add_deadline" => "Chcete pridať deadline odovzdania?",
    "deadline" => "Dátum deadline: ",
    "result" => "Výsledok",
    "result_correctness" => "Správnosť výsledku",
    "show" => "Zobraziť",
    "unsubmitted" => "Neodovzdaná",
    "submitted" => "Odovzdaná"
);

?>